github:
  description: "Attic"
  homepage: https://attic.apache.org/
  labels:
    - apache
    - attic
    - website
    - jekyll
  features:
    # disable issues management: we're using Jira https://issues.apache.org/jira/projects/ATTIC/summary
    issues: false

  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
  autolink_jira:
    - INFRA
    - ATTIC

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@attic.apache.org
  pullrequests: general@attic.apache.org
  jira_options: link label worklog
  jobs: general@attic.apache.org
  discussions: general@attic.apache.org
